[project]
name = "iodd-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Štěpán Venclík", email = "stepan.venclik@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "xsdata[cli,lxml,soap]>=26.1",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
exclude = ["src/iodd_parser/generated"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-comperhensions
    "C4",
    # flake8-builitins
    "A",
    # isort
    "I",
    # # flake8-fixme
    "FIX",
    # flake8-return
    "RET",
]